import { gzipSync } from "node:zlib";
import type { CompiledColumn, CompiledManifest, CompiledParam, CompiledQueryArtifact } from "../runtime/compiled.ts";

function scalarType(sqlType: string, enumValues?: readonly string[]): string {
  if (enumValues !== undefined && enumValues.length > 0)
    return enumValues.map((value) => JSON.stringify(value)).join(" | ");
  const ty = sqlType.toLowerCase();
  if (["int8", "bigint"].includes(ty)) return "bigint";
  if (["int2", "smallint", "int4", "int", "integer", "float4", "real", "float8", "float", "double precision"].includes(ty))
    return "number";
  if (["numeric", "decimal", "text", "varchar", "char", "bpchar", "uuid"].includes(ty)) return "string";
  if (["bool", "boolean"].includes(ty)) return "boolean";
  if (["date", "timestamp", "timestamptz"].includes(ty)) return "Date";
  if (ty === "bytea") return "Uint8Array";
  if (ty === "json" || ty === "jsonb") return "unknown";
  return "unknown";
}

function columnType(column: CompiledColumn): string {
  const base = scalarType(column.sqlType, column.enumValues);
  return column.nullable ? `${base} | null` : base;
}

function paramType(param: CompiledParam): string {
  const base = scalarType(param.sqlType);
  return param.nullable ? `${base} | null` : base;
}

function objectType(
  fields: readonly { readonly name: string; readonly type: string }[],
): string {
  if (fields.length === 0) return "{}";
  return `{ ${fields.map((field) => `${JSON.stringify(field.name)}: ${field.type};`).join(" ")} }`;
}

/** Emits the global exact-literal type registry. Full builds refresh this file. */
export function emitGeneratedModule(
  artifacts: readonly CompiledQueryArtifact[],
  moduleName = "xql",
): string {
  const lines = [
    `import type { GeneratedQueryInfo } from ${JSON.stringify(moduleName)};`,
    ``,
    `// Generated by xql compile. Do not edit by hand.`,
    `declare module ${JSON.stringify(moduleName)} {`,
    `  interface GeneratedQueryRegistry {`,
  ];

  for (const artifact of artifacts) {
    const row = objectType(artifact.columns.map((column) => ({ name: column.name, type: columnType(column) })));
    const params = objectType(artifact.params.map((param) => ({ name: param.name, type: paramType(param) })));
    lines.push(`    ${JSON.stringify(artifact.source)}: GeneratedQueryInfo<${row}, ${params}>;`);
  }

  lines.push(`  }`, `}`, ``);
  return lines.join("\n");
}

/**
 * Emits runtime metadata separately from the global type registry. The runtime
 * module imports the generated registry only for its augmentation side effect;
 * the registry has no dependency back on runtime metadata. This one-way graph
 * lets runtime metadata change without invalidating every generated query type.
 */
export function emitRuntimeManifestModule(
  artifacts: readonly CompiledQueryArtifact[],
  moduleName = "xql",
  typesImport = "./generated.js",
): string {
  const queryMap: Record<string, CompiledQueryArtifact> = {};
  for (const artifact of artifacts) queryMap[artifact.source] = artifact;
  const manifest: CompiledManifest = { version: 1, queries: queryMap };
  const payload = gzipSync(JSON.stringify(manifest)).toString("base64");

  return [
    `import type ${JSON.stringify(typesImport)};`,
    `import { gunzipSync } from "node:zlib";`,
    `import type { CompiledManifest } from ${JSON.stringify(moduleName)};`,
    ``,
    `// Generated by xql compile. Do not edit by hand.`,
    `export const manifest = JSON.parse(`,
    `  gunzipSync(Buffer.from(${JSON.stringify(payload)}, "base64")).toString("utf8"),`,
    `) as CompiledManifest;`,
    ``,
  ].join("\n");
}
