import type { CompiledColumn, CompiledManifest, CompiledParam, CompiledQueryArtifact } from "../runtime/compiled.ts";

function scalarType(sqlType: string, enumValues?: readonly string[]): string {
  if (enumValues !== undefined && enumValues.length > 0)
    return enumValues.map((value) => JSON.stringify(value)).join(" | ");
  const ty = sqlType.toLowerCase();
  if (["int8", "bigint"].includes(ty)) return "bigint";
  if (["int2", "smallint", "int4", "int", "integer", "float4", "real", "float8", "float", "double precision"].includes(ty))
    return "number";
  if (["numeric", "decimal", "text", "varchar", "char", "bpchar", "uuid"].includes(ty)) return "string";
  if (["bool", "boolean"].includes(ty)) return "boolean";
  if (["date", "timestamp", "timestamptz"].includes(ty)) return "Date";
  if (ty === "bytea") return "Uint8Array";
  if (ty === "json" || ty === "jsonb") return "unknown";
  return "unknown";
}

function columnType(column: CompiledColumn): string {
  const base = scalarType(column.sqlType, column.enumValues);
  return column.nullable ? `${base} | null` : base;
}

function paramType(param: CompiledParam): string {
  const base = scalarType(param.sqlType);
  return param.nullable ? `${base} | null` : base;
}

function objectType(
  fields: readonly { readonly name: string; readonly type: string }[],
): string {
  if (fields.length === 0) return "{}";
  return `{ ${fields.map((field) => `${JSON.stringify(field.name)}: ${field.type};`).join(" ")} }`;
}

export function emitGeneratedModule(
  artifacts: readonly CompiledQueryArtifact[],
  moduleName = "xql",
): string {
  const queryMap: Record<string, CompiledQueryArtifact> = {};
  for (const artifact of artifacts) queryMap[artifact.source] = artifact;
  const manifest: CompiledManifest = { version: 1, queries: queryMap };

  const lines = [
    `import type { CompiledManifest, GeneratedQueryInfo } from ${JSON.stringify(moduleName)};`,
    ``,
    `// Generated by xql compile. Do not edit by hand.`,
    `declare module ${JSON.stringify(moduleName)} {`,
    `  interface GeneratedQueryRegistry {`,
  ];

  for (const artifact of artifacts) {
    const row = objectType(artifact.columns.map((column) => ({ name: column.name, type: columnType(column) })));
    const params = objectType(artifact.params.map((param) => ({ name: param.name, type: paramType(param) })));
    lines.push(`    ${JSON.stringify(artifact.source)}: GeneratedQueryInfo<${row}, ${params}>;`);
  }

  lines.push(
    `  }`,
    `}`,
    ``,
    `export const manifest = ${JSON.stringify(manifest, null, 2)} as const satisfies CompiledManifest;`,
    ``,
  );
  return lines.join("\n");
}
