import { createHash } from "node:crypto";
import type {
  CompiledPgType,
  CompiledQueryDescriptor,
  CompiledQueryManifest,
} from "../compiled.ts";
import { resolvePgType } from "./postgres.ts";
import type { CatalogSnapshot } from "./types.ts";

export function typescriptTypeForPgType(type: CompiledPgType): string {
  if (type.sqlType.endsWith("[]")) {
    const element = typescriptTypeForPgType({
      sqlType: type.sqlType.slice(0, -2),
      baseType: type.baseType?.endsWith("[]") ? type.baseType.slice(0, -2) : undefined,
      enumValues: type.enumValues,
    });
    return `readonly (${element})[]`;
  }

  if (type.enumValues && type.enumValues.length > 0)
    return type.enumValues.map((value) => JSON.stringify(value)).join(" | ");

  const name = type.baseType ?? type.sqlType;
  switch (name) {
    case "bool":
    case "boolean": return "boolean";
    case "int2":
    case "smallint":
    case "int4":
    case "int":
    case "integer":
    case "float4":
    case "real":
    case "float8":
    case "float":
    case "double precision": return "number";
    case "int8":
    case "bigint": return "bigint";
    case "numeric":
    case "decimal":
    case "text":
    case "varchar":
    case "char":
    case "uuid": return "string";
    case "timestamp":
    case "timestamptz":
    case "date": return "Date";
    case "bytea": return "Uint8Array";
    case "json":
    case "jsonb": return "unknown";
    default: return "unknown";
  }
}

function maybeNullable(type: CompiledPgType, nullable: boolean): string {
  const base = typescriptTypeForPgType(type);
  return nullable ? `${base} | null` : base;
}

export function generateTypes(
  queries: readonly CompiledQueryDescriptor[],
  moduleName = "xql",
): string {
  const entries = queries.map((query) => {
    const row = query.columns.length === 0
      ? "{}"
      : `{\n${query.columns.map((column) =>
          `        ${JSON.stringify(column.name)}: ${maybeNullable(column, column.nullable)};`,
        ).join("\n")}\n      }`;
    const params = query.params.length === 0
      ? "{}"
      : `{\n${query.params.map((param) =>
          `        ${JSON.stringify(param.name)}: ${maybeNullable(param, param.nullable)};`,
        ).join("\n")}\n      }`;
    return `    ${JSON.stringify(query.source)}: {\n      row: ${row};\n      params: ${params};\n    };`;
  });

  return `// Generated by XQL. Do not edit.\nimport ${JSON.stringify(moduleName)};\n\ndeclare global {\n  namespace XqlGenerated {\n    interface Queries {\n${entries.join("\n")}\n    }\n  }\n}\n\nexport {};\n`;
}

export function createManifest(
  postgresVersion: string,
  queries: readonly CompiledQueryDescriptor[],
): CompiledQueryManifest {
  return {
    version: 1,
    postgresVersion,
    queries: Object.fromEntries(queries.map((query) => [query.source, query])),
  };
}

export function generateManifestModule(manifest: CompiledQueryManifest, moduleName = "xql"): string {
  return `// Generated by XQL. Do not edit.\nimport type { CompiledQueryManifest } from ${JSON.stringify(moduleName)};\n\nexport const xqlManifest = ${JSON.stringify(manifest, null, 2)} as const satisfies CompiledQueryManifest;\n`;
}

export function generateCatalogJson(catalog: CatalogSnapshot): string {
  return `${JSON.stringify(catalog, null, 2)}\n`;
}

/**
 * Stable semantic fingerprint for CI drift checks. PostgreSQL OIDs are excluded
 * because they can change when the same logical schema is recreated.
 */
export function catalogFingerprint(catalog: CatalogSnapshot): string {
  const types = new Map(catalog.types.map((type) => [type.oid, type]));
  const customTypes = catalog.types
    .filter((type) => !["pg_catalog", "information_schema"].includes(type.schema))
    .map((type) => ({
      schema: type.schema,
      name: type.name,
      kind: type.kind,
      resolved: resolvePgType(type.oid, types),
      enumValues: type.enumValues,
    }))
    .sort((a, b) => `${a.schema}.${a.name}`.localeCompare(`${b.schema}.${b.name}`));
  const columns = catalog.columns.map((column) => ({
    schema: column.schema,
    table: column.table,
    name: column.name,
    ordinal: column.ordinal,
    type: resolvePgType(column.typeOid, types),
    nullable: column.nullable,
  }));
  return createHash("sha256")
    .update(JSON.stringify({ customTypes, columns }))
    .digest("hex");
}

function codecExpression(type: CompiledPgType): string {
  if (type.sqlType.endsWith("[]")) {
    return `z.array(${codecExpression({
      sqlType: type.sqlType.slice(0, -2),
      baseType: type.baseType?.endsWith("[]") ? type.baseType.slice(0, -2) : undefined,
      enumValues: type.enumValues,
    })})`;
  }
  if (type.enumValues && type.enumValues.length > 0)
    return `z.enum(${JSON.stringify(type.enumValues)} as const)`;

  const tsType = typescriptTypeForPgType(type);
  const codecName = type.baseType ?? type.sqlType;
  const known = [
    "bool", "boolean", "int2", "smallint", "int4", "int", "integer", "int8", "bigint",
    "float4", "real", "float8", "float", "double precision", "numeric", "decimal", "text",
    "varchar", "char", "timestamp", "timestamptz", "date", "uuid", "bytea", "json", "jsonb",
  ].includes(codecName);
  return known
    ? `castZod[${JSON.stringify(codecName)}] as Codec<${tsType}>`
    : "z.unknown()";
}

/** Generate a SchemaDef snapshot from the real PostgreSQL catalog. */
export function generateSchemaModule(catalog: CatalogSnapshot, moduleName = "xql"): string {
  const types = new Map(catalog.types.map((type) => [type.oid, type]));
  const tables = new Map<string, typeof catalog.columns>();
  for (const column of catalog.columns) {
    const table = column.schema === "public" ? column.table : `${column.schema}.${column.table}`;
    tables.set(table, [...(tables.get(table) ?? []), column]);
  }

  const tableEntries = [...tables.entries()].map(([table, columns]) => {
    const fields = [...columns]
      .sort((a, b) => a.ordinal - b.ordinal)
      .map((item) => {
        const type = resolvePgType(item.typeOid, types);
        const base = `column(${JSON.stringify(type.sqlType)}, ${codecExpression(type)})`;
        return `    ${JSON.stringify(item.name)}: ${item.nullable ? `${base}.nullable()` : base},`;
      })
      .join("\n");
    return `  ${JSON.stringify(table)}: {\n${fields}\n  },`;
  });

  return `// Generated by XQL from PostgreSQL. Do not edit.\nimport { castZod, column, defineSchema, type Codec } from ${JSON.stringify(moduleName)};\nimport { z } from "zod";\n\nexport const schema = defineSchema({\n${tableEntries.join("\n")}\n});\n\nexport default schema;\n`;
}
